
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: apache
          image: php:7.2-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: html
            - mountPath: /usr/local/apache2/conf/httpd.conf
              name: apache-config
              subPath: httpd.conf
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: http-pvc
        - name: apache-config
          configMap:
            name: apacheconf
